DROP TABLE IF EXISTS compilations_events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users(
    id BIGINT generated by default as identity primary key,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories(
    id BIGINT generated by default as identity primary key,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations(
    id BIGINT generated by default as identity primary key,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events(
    id BIGINT generated by default as identity primary key,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    initiator BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category BIGINT NOT NULL REFERENCES categories(id),
    location BIGINT NOT NULL REFERENCES locations(id),
    event_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    created_on TIMESTAMP(0) WITHOUT TIME ZONE,
    published_time TIMESTAMP(0) WITHOUT TIME ZONE,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    paid BOOL NOT NULL DEFAULT FALSE,
    request_moderation BOOL NOT NULL DEFAULT FALSE,
    state VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS requests(
    id BIGINT generated by default as identity primary key,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations(
    id BIGINT generated by default as identity primary key,
    pinned BOOL NOT NULL DEFAULT FALSE,
    title VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations_events(
    compilation_id BIGINT NOT NULL REFERENCES compilations(id),
    event_id BIGINT NOT NULL REFERENCES events(id)
);